version: '3.1'

services:
  mysql:
    container_name: mysql_db
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: recipes
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8081
  recipes-api:
    image: perfectvint/recipes-api
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/recipes?autoReconnect=true&useSSL=false
    depends_on:
      - mysql

volumes:
  my-db: