name: Deploy by runner

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkin
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clearing old images
        run: |
          cd docker
          docker-compose down

      - name: ls
        run: ls -la

      - name: Build and package Spring Boot app
        run: /opt/maven/bin/mvn clean package

      - name: Build Docker image
        run: docker build -t recipes-api:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag recipes-api:latest perfectvint/recipes-api
          docker push ${{secrets.DOCKER_USERNAME}}/recipes-api:latest

      - name: Run the application
        run: |
          cd docker
          docker-compose up -d