name: Deploy buy runner

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test

  deploy:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkin
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: ls
        run: ls -la
#
#      - name: Maven Verify
#        run: mvn -B clean verify

#      - name: Build and package Spring Boot app
#        run: mvn clean package -DskipTests

#      - name: Deploy using Docker Compose
#        run: |
#          cd docker
#          docker-compose up -d