name: Deploy buy runner

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test

  deploy:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkin
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: ls
        run: ls -la

      - name: Build and package Spring Boot app
        run: /opt/maven/bin/mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t recipes-api:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag recipes-api:latest perfectvint/recipes-api
          docker push ${{secrets.DOCKER_USERNAME}}/recipes-api:latest

      - name: Clearing old images
        run: |
          cd docker
          docker-compose down

      - name: Up MySQL DB
        run: |
          docker-compose up -d

      - name: Run the application
        run: |
          cd ..
          /opt/maven/bin/mvn spring-boot:run